name: Bundle App NPM Release

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  call-app-npm-docker:
    uses: Forsakringskassan/.github/.github/workflows/app-npm-docker.yaml@main
    with:
      release: true
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
  call-npm-ghpages-app:
    uses: Forsakringskassan/.github/.github/workflows/npm-ghpages-app.yaml@main
  publish-release:
    needs: call-app-npm-docker
    uses: Forsakringskassan/.github/.github/workflows/publish-release-on-tag-push.yaml@main
