name: Bundle Maven Release

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  check-project-type:
    runs-on: ubuntu-latest
    outputs:
      is-quarkus: ${{ steps.quarkus-check.outputs.is-quarkus }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check if Quarkus project
        id: quarkus-check
        run: |
          if grep -q "quarkus-maven-plugin" pom.xml; then
            echo "is-quarkus=true" >> $GITHUB_OUTPUT
            echo "✅ This is a Quarkus project"
          else
            echo "is-quarkus=false" >> $GITHUB_OUTPUT
            echo "❌ This is not a Quarkus project, will trigger maven-release workflow"
          fi

  call-maven-release:
    needs: check-project-type
    if: needs.check-project-type.outputs.is-quarkus == 'false'
    uses: Forsakringskassan/.github/.github/workflows/maven-release.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}

  call-app-maven-conventional-release:
    if: needs.check-project-type.outputs.is-quarkus == 'true' && ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    needs: [check-project-type]
    uses: Forsakringskassan/.github/.github/workflows/maven-conventional-release.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}

  call-app-maven-docker-quarkus:
    if: needs.check-project-type.outputs.is-quarkus == 'true' && ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    needs: [check-project-type, call-app-maven-conventional-release]
    uses: Forsakringskassan/.github/.github/workflows/app-maven-docker-quarkus.yaml@main
    with:
      release: true
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
