name: Bundle Maven Release

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  check-project-type:
    runs-on: ubuntu-latest
    outputs:
      is-quarkus: ${{ steps.quarkus-check.outputs.is-quarkus }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check if Quarkus project
        id: quarkus-check
        run: |
          if grep -q "quarkus-maven-plugin" pom.xml; then
            echo "is-quarkus=true" >> $GITHUB_OUTPUT
            echo "✅ This is a Quarkus project"
          else
            echo "is-quarkus=false" >> $GITHUB_OUTPUT
            echo "❌ This is not a Quarkus project, will trigger maven-release workflow"
          fi

  call-app-generic-conventional-release:
    if: |
      needs.check-project-type.outputs.is-quarkus == 'true' &&
      ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    needs: [check-project-type]
    uses: Forsakringskassan/.github/.github/workflows/generic-conventional-release.yaml@main

  publish-release:
    if: needs.call-app-generic-conventional-release.outputs.is-new-version == 'true'
    needs: call-app-generic-conventional-release
    uses: Forsakringskassan/.github/.github/workflows/publish-release-on-tag-push.yaml@main

  call-app-maven-docker-quarkus:
    if: |
      needs.check-project-type.outputs.is-quarkus == 'true' &&
      needs.call-app-generic-conventional-release.outputs.is-new-version == 'true' &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: [check-project-type, call-app-generic-conventional-release]
    uses: Forsakringskassan/.github/.github/workflows/app-maven-docker-quarkus.yaml@main
    with:
      release: true
      version: ${{ needs.call-app-generic-conventional-release.outputs.current-version }}
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
