name: Bundle Maven Release

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  call-maven-ci:
    uses: Forsakringskassan/.github/.github/workflows/maven-release.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
  call-publish-release:
    needs: call-maven-ci
    uses: Forsakringskassan/.github/.github/workflows/publish-release-on-tag-push.yaml@main
