name: Bundle Maven CI

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  call-maven-ci:
    uses: Forsakringskassan/.github/.github/workflows/maven-ci.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
  call-app-maven-docker-quarkus:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    needs: call-maven-ci
    uses: Forsakringskassan/.github/.github/workflows/app-maven-docker-quarkus.yaml@main
    with:
      release: false
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
  call-pnr-scan:
    uses: Forsakringskassan/.github/.github/workflows/pnr-scanner.yaml@main
