#
# Använd bundle-maven-quarkus direkt istället!
# Har kvar den är bara för att inte behöva ändra så mycket.
#
name: Bundle Maven Release

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  call-bundle-maven-quarkus-release:
    uses: Forsakringskassan/.github/.github/workflows/bundle-maven-quarkus-release.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
