name: Gradle CI

on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    env:
      skip-automatic-fk-code-standard-apply: true
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: "1"
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "25"
          cache: 'gradle'
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-v1
      - name: prepare Gradle
        shell: bash
        run: |
          mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - name: Check formatting
        shell: bash
        run: |
          ./gradlew --no-daemon spotlessJavaCheck
        env:
          PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
          PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
      - name: "Gradle build"
        shell: bash
        run: |
          java -version
          javac -version
          ./gradlew --no-daemon build
        env:
          PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
          PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}

      - name: Transorm static code analysis to SARIF
        if: ${{ (success() || failure()) }}
        run: |
          npx violations-command-line -sarif sarif-report.json \
          -v "FINDBUGS" "." ".*build/reports/spotbugs/main\.xml$" "Spotbugs" \
          -v "CHECKSTYLE" "." ".*build/reports/checkstyle/main\.xml$" "Checkstyle" \
          -v "PMD" "." ".*build/reports/pmd/main\.xml$" "PMD" \
          -v "JUNIT" "." ".*/build/test-results/test/TEST-.*\.xml$" "JUNIT"
      - uses: github/codeql-action/upload-sarif@v4
        if: ${{ (success() || failure()) }}
        with:
          sarif_file: sarif-report.json
          category: violations-lib

      - name: Publish Build
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-${{ github.run_number }}
          path: ${{ github.workspace }}
