name: Maven Conventional Release


on:
  workflow_call:
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  maven-conventional-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-tags: "true"
          fetch-depth: "0"

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "zulu"
          cache: 'maven'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-v1

      - name: Git User
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "nobody@fk.se"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create Maven settings.xml
        run: |
          mkdir -p "$RUNNER_TEMP/maven"
          cat <<'EOF' > "$RUNNER_TEMP/maven/settings.xml"
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github--Forsakringskassan--repository</id>
                <username>${env.PACKAGES_RW_ACTOR}</username>
                <password>${env.PACKAGES_RW_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Set version
        run: |
          nextVersion=$(npx git-changelog-command-line \
            --print-next-version)
          ./mvnw -s $RUNNER_TEMP/maven/settings.xml -q versions:set -DnewVersion=${nextVersion} -DprocessAllModules=true
          git commit -a -m "chore: setting ${nextVersion} version in pom" || echo "No changes to commit"
          git tag $nextVersion
        env:
          PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
          PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}

      - name: Update changelog
        run: |
          highestTag=$(npx git-changelog-command-line \
            --print-highest-version-tag)
          echo Last release detected as $highestTag

          npx git-changelog-command-line \
            --ignore-pattern ".*maven-release-plugin.*" \
            -of CHANGELOG.md

          git add CHANGELOG.md
          git commit -a -m "chore: updating changelog" || echo "No changes to commit"
          git push
          git push --tags
