name: Maven Release


on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      PACKAGES_RW_ACTOR:
        required: true
      PACKAGES_RW_TOKEN:
        required: true

jobs:
  maven-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "zulu"
          cache: 'maven'

      - name: Create Maven settings.xml
        run: |
          mkdir -p "$RUNNER_TEMP/maven"
          cat <<'EOF' > "$RUNNER_TEMP/maven/settings.xml"
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github--Forsakringskassan--repository</id>
                <username>${env.PACKAGES_RW_ACTOR}</username>
                <password>${env.PACKAGES_RW_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Git User
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "nobody@fk.se"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Set version
        run: |
          export MAVEN_OPTS="$MAVEN_OPTS -ntp -s $RUNNER_TEMP/maven/settings.xml -T 1C"
          ./mvnw versions:set -DnewVersion=${{ inputs.version }} -DprocessAllModules=true

      - name: Publish with Maven
        run: |
          export MAVEN_OPTS="$MAVEN_OPTS -ntp -s $RUNNER_TEMP/maven/settings.xml -T 1C"
          ./mvnw package deploy
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
          PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
