name: NPM Component Test

on: [workflow_call]

jobs:
  cypress-ct:
    name: Cypress Component Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Use Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build (minimal)
        run: npm run build
      - name: Cypress Component Testing
        uses: cypress-io/github-action@v6
        with:
          summary-title: "Component tests"
          browser: chrome
          component: true
          quiet: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
