name: PNR Scan

on: [workflow_call]

permissions:
  contents: read

jobs:
  pnr-scan:
    name: PNR Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-pnr-scanner
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: pnr-scanner
        run: |
          errors=$(npx pnr-scanner . 2> /dev/null | egrep "    " | wc -l)
          if [[ "${errors}" != "0" ]]; then
              echo "Found ${errors} potential personnummer. Rerun `npx pnr-scanner .` locally for more information."
              exit 1
          fi
