name: Publish release on tag push

on:
  workflow_call:

jobs:
  publish-github-release-from-latest-tag:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-tags: "true"
          fetch-depth: "0"
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: 17
      - uses: tomasbjerre/git-changelog-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
