# Renovate needs credentials to do this, cannot get that working with the Github Renovate App.

name: Renovate Maven/Gradle packages published to GitHub Packages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_KEY }}

      - name: Create Renovate config
        run: |
          cat <<EOF > renovate.json
          {
            "\$schema": "https://docs.renovatebot.com/renovate-schema.json",
            "extends": ["config:base"],
            "enabledManagers": ["gradle", "maven"],
            "hostRules": [
              {
                "hostType": "maven",
                "matchHost": "maven.pkg.github.com",
                "username": "${{ steps.app-token.outputs.app-slug }}[bot]",
                "password": "${{ steps.app-token.outputs.token }}"
              }
            ],
            "packageRules": [
              {
                "matchManagers": ["gradle", "maven"],
                "matchPackagePrefixes": ["se.fk"],
                "enabled": true
              },
              {
                "matchManagers": ["gradle", "maven"],
                "excludePackagePrefixes": ["se.fk"],
                "enabled": false
              }
            ],
            "labels": ["deps", "internal-se.fk"],
            "automerge": false
          }
          EOF

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.16
        env:
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
          LOG_LEVEL: debug
          GITHUB_COM_TOKEN: ${{ steps.app-token.outputs.token }}
          RENOVATE_PLATFORM: github
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "Forsakringskassan/template-quarkus"
        with:
          configurationFile: renovate.json
          token: ${{ steps.app-token.outputs.token }}
