# Renovate needs credentials to do this, cannot get that working with the Github Renovate App.

name: Renovate Maven/Gradle packages published to GitHub Packages

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Create Renovate config
              run: |
                  cat <<'EOF' > renovate.json
                  {
                    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
                    "extends": ["config:base"],
                    "enabledManagers": ["gradle", "maven"],
                    "hostRules": [
                      {
                        "hostType": "maven",
                        "matchHost": "maven.pkg.github.com",
                        "username": "${{ secrets.PACKAGES_RW_ACTOR }}",
                        "password": "${{ secrets.PACKAGES_RW_TOKEN }}"
                      }
                    ],
                    "packageRules": [
                      {
                        "matchManagers": ["gradle", "maven"],
                        "matchPackagePrefixes": ["se.fk"],
                        "enabled": true
                      },
                      {
                        "matchManagers": ["gradle", "maven"],
                        "excludePackagePrefixes": ["se.fk"],
                        "enabled": false
                      }
                    ],
                    "labels": ["deps", "internal-se.fk"],
                    "automerge": true
                  }
                  EOF

            - name: Run Renovate
              uses: renovatebot/github-action@v40
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  configurationFile: renovate.json
